module.exports = {
	"1": "Running",
	"2": "Nordic Walking",
	"3": "Cycling",
	"4": "Mountain Biking",
	"5": "Other",
	"6": "Skating",
	"7": "Hiking",
	"8": "Cross Country Skiing",
	"9": "Skiing",
	"10": "Snow Boarding",
	"11": "Motorbiking",
	"13": "Snowshoeing",
	"14": "Running (Treadmill)",
	"15": "Cycling (Ergometer)",
	"16": "Elliptical",
	"17": "Rowing",
	"18": "Swimming",
	"19": "Walking",
	"20": "Riding",
	"21": "Golfing",
	"22": "Race Cycling",
	"23": "Tennis",
	"24": "Badminton",
	"25": "Squash",
	"26": "Yoga",
	"27": "Aerobics",
	"28": "Martial Arts",
	"29": "Sailing",
	"30": "Windsurfing",
	"31": "Pilates",
	"32": "Climbing",
	"33": "Frisbee",
	"34": "Strength Training",
	"35": "Volleyball",
	"36": "Handbike",
	"37": "Cross Skating",
	"38": "Soccer",
	"42": "Surfing",
	"43": "Kite Surfing",
	"44": "Kayaking",
	"45": "Basketball",
	"46": "Spinning",
	"47": "Paragliding",
	"48": "Wake Boarding",
	"50": "Diving",
	"51": "Table Tennis",
	"52": "Handball",
	"53": "Back Country Skiing",
	"54": "Ice Skating",
	"55": "Sledding",
	"58": "Curling",
	"60": "Biathlon",
	"61": "Kite Skiing",
	"67": "American Football",
	"68": "Baseball",
	"69": "Crossfit",
	"70": "Dancing",
	"71": "Ice Hockey",
	"72": "Skateboarding",
	"73": "Zumba",
	"74": "Gymnastics",
	"75": "Rugby",
	"76": "Standup Paddling"
}